// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");

console.log("Hello, World!");

var x = {
  contents: 5
};

x.contents = x.contents + 1 | 0;

console.log(x);

console.log("Helloworld");

console.log(true);

console.log(false);

console.log(false);

console.log("test");

console.log(3);

console.log(3.1415);

console.log(8);

console.log(2);

var point = {
  x: 20,
  y: "test"
};

console.log(point);

var myArray = [
  1,
  2,
  3
];

console.log(myArray);

Caml_array.set(myArray, 1, 0);

console.log(myArray);

var myarraty = [
  1,
  "Bob",
  true
];

console.log(myarraty);

console.log("test");

function named(arg) {
  console.log(arg);
  
}

exports.x = x;
exports.point = point;
exports.myArray = myArray;
exports.myarraty = myarraty;
exports.named = named;
/*  Not a pure module */
